In [1]:
import numpy as np

## Data Types and Arrays

In [2]:
#ndarray means n-dimensional array
a1 = np.array([[1,2,3],[3,2,1]])
type(a1)
a1.size,a1.ndim

(6, 2)

## Creating a DF from a numpy array

In [3]:
import pandas as pd
df = pd.DataFrame(a1)


In [4]:
ones = np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
zeroes = np.zeros([3,3])
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
range_array = np.arange(0,20,5)
range_array

array([ 0,  5, 10, 15])

In [7]:
temp = np.random.randint(0,30, size = (2,4))
temp

array([[16, 29,  7, 24],
       [26, 12,  4, 21]])

In [8]:
np.random.random((10, 10))

array([[0.44729659, 0.77394707, 0.18248744, 0.22870783, 0.86131634,
        0.61628374, 0.2104265 , 0.4807604 , 0.49350966, 0.48580015],
       [0.83882908, 0.6055195 , 0.89302067, 0.78487714, 0.01075159,
        0.62345359, 0.33458041, 0.07822713, 0.83452669, 0.76663591],
       [0.45086857, 0.95997642, 0.99803886, 0.26942901, 0.89263111,
        0.18032378, 0.89842188, 0.70128778, 0.1826312 , 0.56729653],
       [0.78692277, 0.83057508, 0.56765251, 0.13195008, 0.64743833,
        0.41164321, 0.08243891, 0.60164797, 0.67839948, 0.93633888],
       [0.86046984, 0.93390407, 0.02829107, 0.29624912, 0.71875586,
        0.20976772, 0.20760123, 0.1750984 , 0.13541025, 0.81379933],
       [0.30333949, 0.14235445, 0.17270419, 0.01471162, 0.78496986,
        0.79167371, 0.69094109, 0.36358627, 0.95950038, 0.3674329 ],
       [0.29578782, 0.83371761, 0.4121146 , 0.89140139, 0.00235099,
        0.62283808, 0.56719823, 0.56090251, 0.17303562, 0.85522929],
       [0.89129767, 0.17065704, 0.4171455

In [9]:
#random number seeds
np.random.seed(seed=100)
randArray = np.random.randint(100, size=(5,5))
randArray[:]

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27]])

Viewing Arrays and Matricies

In [10]:
#finding unique elements in an array
np.unique(randArray)

array([ 2,  8,  9, 10, 14, 15, 16, 24, 27, 34, 48, 52, 53, 58, 60, 66, 67,
       79, 86, 87, 93, 94, 98])

In [11]:
#getting a higher dimensional array is a matrix
randMat = np.random.randint(10, size = (2,3,4,5))
randMat

array([[[[4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9],
         [9, 3, 2, 5, 8]],

        [[1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2],
         [8, 3, 5, 0, 9]],

        [[3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6],
         [2, 4, 2, 7, 1]]],


       [[[6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0],
         [5, 9, 6, 6, 5]],

        [[6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6],
         [2, 3, 4, 8, 9]],

        [[8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2],
         [3, 6, 4, 1, 3]]]])

In [12]:
#getting the first four numbers of the inner most array
randMat[:,:,:,4]

array([[[4, 1, 9, 8],
        [2, 1, 2, 9],
        [7, 4, 6, 1]],

       [[2, 4, 0, 5],
        [9, 1, 6, 9],
        [5, 6, 2, 3]]])

In [13]:
np.ones((2,3,4,5)) + randMat

array([[[[ 5.,  2.,  6.,  4.,  5.],
         [ 5.,  4.,  8.,  2.,  2.],
         [ 8.,  8.,  1.,  3., 10.],
         [10.,  4.,  3.,  6.,  9.]],

        [[ 2.,  1.,  8.,  7.,  3.],
         [ 1.,  9.,  3.,  6.,  2.],
         [ 9.,  2.,  6.,  5.,  3.],
         [ 9.,  4.,  6.,  1., 10.]],

        [[ 4.,  7.,  4.,  5.,  8.],
         [ 7.,  4., 10.,  1.,  5.],
         [ 5.,  6.,  8.,  7.,  7.],
         [ 3.,  5.,  3.,  8.,  2.]]],


       [[[ 7.,  7.,  1.,  8.,  3.],
         [ 4.,  6.,  5.,  3.,  5.],
         [ 4.,  8., 10.,  1.,  1.],
         [ 6., 10.,  7.,  7.,  6.]],

        [[ 7.,  5.,  8.,  4., 10.],
         [ 3.,  4.,  9.,  8.,  2.],
         [ 6., 10.,  4.,  1.,  7.],
         [ 3.,  4.,  5.,  9., 10.]],

        [[ 9.,  6.,  3.,  8.,  6.],
         [10.,  1., 10.,  9.,  7.],
         [ 3.,  1.,  6.,  4.,  3.],
         [ 4.,  7.,  5.,  2.,  4.]]]])

## How to reshape numpy array

In [14]:
randArray * randMat

ValueError: operands could not be broadcast together with shapes (5,5) (2,3,4,5) 

In [ ]:
temp = np.random.randint(10, size=(2,3))


In [20]:
temp = pd.DataFrame(np.random.randint(20, size = (2,2)))
bigArray = np.random.random(1000000)


In [21]:
%timeit sum(bigArray)
%timeit np.sum(bigArray)

111 ms ± 2.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
998 µs ± 12.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [24]:
#variance = measure of the average degree to which a number is different from another number
#higher variance implies a wider range of numbers
#lower variance implies a lower range of numbers

np.var(bigArray)

0.0832949912743189

In [25]:
np.sqrt(np.var(bigArray))

0.28860871655984144

In [27]:
np.std(bigArray)

0.28860871655984144

In [30]:
a2 = np.array([[1,2,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [36]:
a2.reshape(2,3,1)*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [42]:
mat1= np.random.randint(10, size=(5,3))
mat2= np.random.randint(10, size=(5,3))


In [55]:
print(mat1)
print(mat2)

#hadamard product
print("the elementwise product is: \n   ",mat1 *mat2)

#dot product and transpose
print("the dot product with a single transpose is: \n", np.dot(mat1,mat2.T))

[[1 0 7]
 [0 9 0]
 [2 7 0]
 [9 4 2]
 [1 2 9]]
[[3 0 2]
 [4 8 7]
 [4 9 5]
 [3 9 7]
 [5 3 9]]
the elementwise product is: 
    [[ 3  0 14]
 [ 0 72  0]
 [ 8 63  0]
 [27 36 14]
 [ 5  6 81]]
the dot product with a single transpose is: 
 [[17 53 39 52 68]
 [ 0 72 81 81 27]
 [ 6 64 71 69 31]
 [31 82 82 77 75]
 [21 83 67 84 92]]


## Dot Product Example

In [56]:
np.random.seed(1)
#number of jars sold over 5 days with size = (type,days)
sales_amount = np.random.randint(7, size=(5,3))


In [65]:
#weekly sales dataframe
weeklySales = pd.DataFrame(sales_amount, index=["mon","tue","wed","thur","fri"],
columns = ["almond butter", 'peanut butter', 'cashew butter'])

weeklySales

almond butter  peanut butter  cashew butter
mon               5              3              4
tue               0              1              3
wed               5              0              0
thur              1              4              5
fri               4              6              1

In [69]:
price = np.array([10,8,12])
buttaPrices = pd.DataFrame(price.reshape(1,3), index = ["price"], columns=["almond butter","peanut butter", "cashew butter"])


In [71]:
buttaPrices

almond butter  peanut butter  cashew butter
price             10              8             12

In [75]:
#to get the totals, we use a dot product but the shapes need to be aligned

totalSales = price.dot(sales_amount.T )