# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
oneD = np.random.randint(10,size=(1,10))
oneD
# Create a 2-dimensional NumPy array using np.array()
twoD = np.random.randint(10,size=(2,10))
twoD

# Create a 3-dimensional Numpy array using np.array()
threeD = np.random.randint(10,size=(3,10))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
oneD.ndim, oneD.dtype, oneD.size, oneD.shape


(2, dtype('int64'), 10, (1, 10))

In [5]:
# Attributes of 2-dimensional array
#same as above but replace ndarray name
import pandas as pd

In [6]:
# Attributes of 3-dimensional array
#same as above but replace ndarray name

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
oneDdf = pd.DataFrame(oneD)

In [8]:
# Create an array of shape (10, 2) with only ones
onsies = np.ones(shape = (10,2))
onsies

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
# Create an array of shape (7, 2, 3) of only zeros
zeerohs = np.zeros(shape=(7,2,3))
zeerohs

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
# Create an array within a range of 0 and 100 with step 3
stepThree = np.arange(0,100,3)
stepThree

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [55]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randArray = np.random.uniform(low=0.0, high=10.0, size=(7,2))
randArray

array([[8.43154675, 9.61878242],
       [2.46141852, 6.88797436],
       [2.95099045, 0.42016383],
       [4.04683387, 9.46580096],
       [2.05459787, 9.96143443],
       [2.32211077, 0.32851258],
       [9.41326503, 0.41644533]])

In [56]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randArray = np.random.random(size=(3,5))
randArray

array([[0.5857864 , 0.77434866, 0.85662835, 0.22166226, 0.99111481],
       [0.32679331, 0.32467256, 0.49140311, 0.02986887, 0.16825731],
       [0.91967657, 0.79846501, 0.3683741 , 0.983082  , 0.88859154]])

In [58]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
seededRandArray = np.random.uniform(0,10,size=(4,6))
seededRandArray

array([[3.74540119, 9.50714306, 7.31993942, 5.98658484, 1.5601864 ,
        1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012, 7.08072578, 0.20584494,
        9.69909852],
       [8.32442641, 2.12339111, 1.81824967, 1.8340451 , 3.04242243,
        5.24756432],
       [4.31945019, 2.9122914 , 6.11852895, 1.39493861, 2.92144649,
        3.66361843]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [59]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
randomItejers = np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(randomItejers)


array([2, 3, 4, 5, 7, 8, 9])

In [15]:
# Find the 0'th index of the latest array you created
randomItejers[0]

In [61]:
# Get the first 2 rows of latest array you created
randArray[0:2]

array([[0.5857864 , 0.77434866, 0.85662835, 0.22166226, 0.99111481],
       [0.32679331, 0.32467256, 0.49140311, 0.02986887, 0.16825731]])

In [66]:
# Get the first 2 values of the first 2 rows of the latest array
randomItejers[0:2,0:2]

array([[3, 7],
       [7, 5]])

In [70]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x = np.random.randint(0,10,size=(3,5))
y = np.ones(shape=(3,5))

In [71]:
# Add the two arrays together
y + x

array([[ 7.,  9.,  8.,  1.,  8.],
       [ 8.,  3.,  1.,  8.,  3.],
       [ 3.,  1.,  5., 10.,  7.]])

In [72]:
# Create another array of ones of shape (5, 3)
z = np.ones(shape=(5,3))

In [73]:
# Try add the array of ones and the other most recent array together
x + y + z

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [76]:
# Create another array of ones of shape (3, 5)
y.shape

(3, 5)

In [78]:
# Subtract the new array of ones from the other most recent array
z-y.reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# Multiply the ones array with the latest array


In [25]:
# Take the latest array to the power of 2 using '**'


In [26]:
# Do the same thing with np.square()


In [27]:
# Find the mean of the latest array using np.mean()


In [28]:
# Find the maximum of the latest array using np.max()


In [29]:
# Find the minimum of the latest array using np.min()


In [30]:
# Find the standard deviation of the latest array


In [31]:
# Find the variance of the latest array


In [32]:
# Reshape the latest array to (3, 5, 1)


In [33]:
# Transpose the latest array


What does the transpose do?

In [82]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed()
rand1 = np.random.randint(10, size=(3,2))
rand2 = np.random.randint(10,size=(2,3))
rand1,rand2

(array([[9, 9],
        [2, 1],
        [3, 4]]),
 array([[8, 4, 7],
        [8, 4, 6]]))

In [83]:
# Perform a dot product on the two newest arrays you created
rand1.dot(rand2)

array([[144,  72, 117],
       [ 24,  12,  20],
       [ 56,  28,  45]])

In [84]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand1 = np.random.randint(10,size=(4,3))
rand2 = np.random.randint(10,size=(4,3))
rand1,rand2


(array([[6, 4, 6],
        [4, 7, 4],
        [6, 9, 2],
        [2, 5, 0]]),
 array([[0, 5, 6],
        [7, 7, 4],
        [6, 5, 7],
        [1, 4, 5]]))

In [85]:
# Perform a dot product on the two newest arrays you created
rand1.dot(rand2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [86]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
rand1.dot(rand2.T)

array([[ 56,  94,  98,  52],
       [ 59,  93,  87,  52],
       [ 57, 113,  95,  52],
       [ 25,  49,  37,  22]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [102]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
randA1 = np.random.randint(10, size=10)
randA2 = np.random.randint(10, size=10)
randA1,randA2

(array([0, 6, 6, 4, 6, 0, 2, 9, 8, 8]), array([8, 8, 1, 0, 1, 8, 4, 0, 7, 9]))

In [90]:
# Compare the two arrays with '>'
randA1 > randA2

array([[ True,  True,  True,  True, False, False,  True, False,  True,
        False]])

What happens when you compare the arrays with `>`?

In [103]:
# Compare the two arrays with '>='
randA1 >= randA2


array([False, False,  True,  True,  True, False, False,  True,  True,
       False])

In [107]:
# Find which elements of the first array are greater than 7
np.argwhere(randA1>7)


array([[7],
       [8],
       [9]])

In [111]:
# Which parts of each array are equal? (try using '==')
np.argwhere(randA1 == randA2)


array([False, False, False, False, False, False, False, False, False,
       False])

In [113]:
# Sort one of the arrays you just created in ascending order
np.sort(rand1)


array([[4, 6, 6],
       [4, 4, 7],
       [2, 6, 9],
       [0, 2, 5]])

In [114]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand1)

array([[1, 0, 2],
       [0, 2, 1],
       [2, 0, 1],
       [2, 0, 1]])

In [118]:
# Find the index with the maximum value in one of the arrays you've created
np.argsort(rand1)[:,-1]

array([2, 1, 1, 1])

In [119]:
# Find the index with the minimum value in one of the arrays you've created
np.argsort(rand1)[:,0]

array([1, 0, 2, 2])

In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [126]:
# Create an array of normally distributed random numbers
randNorm = np.random.normal(size=20)
randNorm

array([-2.06695624, -0.34916075, -1.13271079,  0.37597697, -0.4638897 ,
        1.43333093, -0.75878682,  1.26141078,  0.8132603 ,  0.77916847,
       -0.76658007, -1.28210331, -0.41084004,  0.26122903, -1.62881561,
       -1.34686608,  1.43626738, -0.46641954,  0.42198114, -1.88614949])

In [129]:
# Create an array with 10 evenly spaced numbers between 1 and 100
temp = np.arange(0,101, 20)
temp

array([  0,  20,  40,  60,  80, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.